export const COMPANIES = [
  "99", "100 Open Startups", "Abbott", "ABStartups", "Academia Brasileira de Artes",
  "Accenture", "Accor", "Ache", "Acotel", "ADP Brazil Labs", "AES Brasil",
  "Agencia Africa", "AgiBank", "Ágora", "Agroforte", "Agsus AgroNegocios",
  "Air Liquide", "Akzo Nobel", "Alcatel", "Alcoa", "Alelo", "ALERJ",
  "Algar Telecom", "Allianz Seguros", "Alpargatas", "Amazon", "Ambev",
  "AmCham", "AMDOCS", "American Express", "Americanas", "Anatel",
  "Andre Almeida Adv", "Anglo American", "Anglo Gold", "Anhanguera Educacional",
  "Anjos do Brasil", "AOL Buscas", "Apex Brasil", "Arauco", "Arcelor Mittal",
  "Arezzo", "ASA Applied Science Associates", "AstraZeneca", "Atento", "Atos",
  "Aurora Alimentos", "AutoPass", "AVB (Amazonia Venture Hub)", "Avon",
  "B&B Hotels", "B3", "Banco ABN Amro", "Banco BoaVista", "Banco Carrefour",
  "Banco Chase", "Banco da Amazonia", "Banco Daycoval", "Banco do Brasil",
  "Banco dos BRICS (NDB)", "Banco FIAT", "Banco Inter", "Banco Mercantil do Brasil",
  "Banco Mundial", "Banco Nacional", "Banco Nacional do Nordeste", "Banco PAN",
  "Banco Pine", "Banco Safra", "Banco Yamaha", "Band (Rede Bandeirantes)",
  "Bango", "Bank of America", "BankBoston", "BASF", "BASF Farma", "Bayer",
  "Belgo Bekaert", "Bhoeringer Ingelheim", "Bling", "Blip", "BMG", "BNDES",
  "Boa Safra", "Bob’s", "Bonexo", "BP", "BR Distribuidora", "Bracken",
  "Bradesco", "Bradesco Seguros", "BrasilPrev", "BRF Brasil Foods Perdigao",
  "Brinks Inc", "British Government", "Brookfield", "BTG Pactual", "Bunge",
  "Burger King", "C&A", "C6", "C6 Seguradora", "Cabify", "Caixa Economica Federal",
  "Caixa Seguradora", "Capgemini", "Cargill", "Carlyle", "Carrefour",
  "Carta Fabril", "Casas Bahia", "Catho", "CDL Uberlandia", "Centauro (grupo SBF)",
  "Centro de Pesquisas em Energia Elétrica (CEPEL)", "Centro Médico Cirúrgico São Paulo",
  "Centro Universitário Clarentiano", "Cetelem Brasil", "Cetelem Mexico", "CGI",
  "Chevrolet Argentina", "Chevrolet Europa", "Chevron", "Chilli Beans", "CIELO",
  "Cimento Mata", "Citibank", "Claro", "ClickBus", "Climatempo", "Clube Melissa",
  "CNI", "Coca-Cola", "ColaboraApp", "Colégio Bahiense", "Colégio Bonfim",
  "Colegio Franciscano Pio XII", "Colégio Marista", "Colégio Paulo Freire",
  "Colegio Sagrado Coração de Jesus", "Companhia Paranaense de Energia - Copel",
  "Concentrix", "Concremat", "Condor", "Conquer", "CONTAX", "Cooperativa Vinícola Aurora",
  "Correios", "CPFL Energias", "CPqD", "CRA RJ", "CREA MS", "Credit Suisse",
  "Crefisa", "CSN", "CSU", "Cube de Regatas Flamengo", "Cultura Inglesa", "CVC",
  "Cyrella", "Danone", "DASA", "Dassault Systems", "Datafolha", "Decathlon",
  "Defensoria Pública do Estado de SP", "Delloitte", "Diageo", "Digible", "Disney",
  "DIVEO", "DoctorWeb", "Drogavet", "Duratex", "Eaton ltda", "Efund Investimentos",
  "Egon Zehnder", "Elabora Social", "Electrolux", "Elektro", "Eletronorte",
  "Embraco", "Embraer", "Embrapa", "Embratel", "Endeavor", "EndeRed/ Ticket",
  "Enel", "Energisa", "Enerst Young", "Engesa", "Ericsson", "ESPM Rio Grande do Sul",
  "ESPN", "Estadão", "Europ Assistance", "Expresso São Miguel", "ExxonMobil",
  "Faber Castel", "Faculdade Fisul", "Faculdade Senac", "Fast Shop", "FATEC",
  "FCamara", "FCJ Venture Builder", "FeComercio", "Femsa", "Ferro+", "FGV",
  "FGV, Arbache Innovations", "FIAT", "Fidelity", "FIESP", "Firjan",
  "Folha de São Paulo", "Ford", "Fortaleza Esporte Clube", "Frigorifico Borrússia",
  "Fujitsu", "Furukawa", "G1", "Gafisa", "Gatorade", "Gelato Diletto",
  "General Motors Brasil", "Gerdau", "Getnet", "Getronics", "GFT Technologies",
  "Globex", "GOL", "Google", "GPA", "Great Place to Work", "Greenfield Global Opportunities",
  "Greenpace", "Grendene", "Grupo 3 Corações", "Grupo Aliança", "Grupo BNP Paribas",
  "Grupo Boticário", "Grupo EcoRodovías", "Grupo Fleury", "Grupo Hinode",
  "Grupo Pão de Açúcar", "Grupo Petrópolis", "Grupo Publicis", "Grupo RBS",
  "Grupo Seres", "Grupo Setal", "Grupo Votorantim", "Gulf Capital Partners",
  "GVT", "Gympass", "Habib’s", "HapVida", "HBO", "Heinkein", "Henkel México",
  "Hilti", "Hipercadr", "Hitachi America (USA)", "Hitachi Energy", "Honda",
  "Honeywell", "Honor", "HortiFruti", "Hospital Albert Einstein", "Hospital Alemão Oswaldo Cruz",
  "Hospital Beneficência Portuguesa", "Hospital Beneficiencia Portuguesa",
  "Hospital Santa Catarina", "Hospital Santo Antonio", "Hospital São Luiz",
  "Hostgator", "Hotmart", "HP", "HSBC", "Huawei", "Hyundai", "IBGE",
  "Ibiza Preservation", "IBM", "Icatu", "IFood", "Igua Saneamento",
  "Industrias São Miguel", "Infojobs", "Intel", "Intelbras", "Intelecto Contact Center",
  "InterCapital", "InterCement", "Intercom", "Intermédica", "Ipiranga",
  "iSE Business School", "Itaú", "Itausa", "IUGU", "JBS", "Johnson & Johnson",
  "Jornal do Povo", "Joule Asset Management", "JP Morgan", "JUNO", "Justo",
  "Kaizen Company", "Kearney", "Klabin", "Klin Calçados Infantis",
  "Konica Minolta Brasil", "Kopenhagen", "Korn Ferry", "KPMG", "Kroton",
  "Kroton Educacional", "L' occitane", "Lacoste", "Lanxess", "LATAM Airlines",
  "Lavazza", "Lee Hecht Harrison", "Leffosse", "Lello Condomínios", "LENOVO",
  "Leo Burnett", "Levi’s", "LG", "LHH - Lee Hecht Harrison", "Libbs",
  "Liberta Investimentos", "Light", "Linkedin", "LionBridge", "Localiza",
  "Locaweb", "Loggi", "Loreal", "Madeira Madeira", "Magazine Luiza", "Makro",
  "Malwee", "Mapfre Seguros", "Marinha do Brasil", "Marketdata", "Mars",
  "MATH Group", "Mc Donald’s", "Mckinsey", "Med Grupo", "Medtronic",
  "Melnick Even", "Mercado Bitcoin", "Mercado Livre", "Mercedes Bens", "Merck",
  "Mesbla", "Meta (Facebook)", "Metlife Seguros", "Michael Page", "Microsoft",
  "MIT Professional Educations", "Mondial Assistance", "Monsanto",
  "Mosaic Fertilizantes", "Motorola", "Motz", "Movida", "Movile", "MRV",
  "Multilazer", "Museu da República", "Museu Oscar Niemeyer", "Mutant",
  "Natura", "Nestlé", "NEXA Ressources", "Nextel", "Nielsen", "Nike", "Nissan",
  "Nívea", "Nokia", "Norsk Hydro", "NotreDame", "Nova América Textil",
  "Novartis", "NTTData", "Nubank", "NutriControl", "OESP Mídia", "Oi",
  "OnFrontiers", "ONG Gerando Falcoes", "ONG Instituto de Medicina e Cidadania",
  "ONU", "Oracle", "Organização Educacional Farias Brito", "Organização Pan Americana de Saúde",
  "Orizon", "Osklen", "Otica Real", "Oxiteno", "OXXO Brasil", "P&G", "Panasonic",
  "Panco", "Park Máquinas", "Parque Tecnológico de Sorocaba", "Patria Investimentos",
  "Pearson", "Pedro Toledo Piza Advocacia", "Peixe Urbano", "Pepsi", "Petrobras",
  "Phillips Morris", "PicPay", "Pipedrive", "Plamev", "Plena Cardiologia",
  "Porche", "Porto Seguro", "PortoBello", "Positivo Tecnologia", "Prevent Senior",
  "PrimeTime", "Promon", "PUC Goiás", "PUC Minas Gerais", "PUC PR", "PUC SP",
  "PWR Gestão", "Qintess", "Raizen", "Rascal/ Vienna", "RD Station", "RDC TV",
  "Reckitt Benkiser", "Rede Globo", "Rede Mulher Empreendedora", "Rede Record",
  "Rede Salesiana", "Renault do Brasil", "Renner", "Revista Veja São Paulo",
  "Rhodia", "Riachuelo", "Rio Bravo Investimentos", "Rio Innovation Week",
  "Rio Saneamento", "Roche", "Rock n Rio", "Royal FIC", "RVC Advogados",
  "Saint Antony Parish Massachusetts", "Salesforce", "Samarco", "Samsung",
  "Sanepar", "Sanofi", "Santa Casa de São Paulo", "Santa Catarina Angels",
  "Santander", "SAP", "SBT", "Schering-Plough (Mantecorp)", "SCPC", "Seara",
  "SEBRAE Maranhão", "Sebrae Nacional", "SEBRAE RS", "SEBRAE São Paulo",
  "Seed Inova", "Semantic", "SENAC Ceará", "Senac Distrito Federal",
  "SENAC Minas Gerais", "Senac Minas Gerais", "Senac Pelotas RS", "Senac São Paulo",
  "Senai Blumenau SC", "Senofi", "Serasa", "Serra Verde Mineração", "Shell",
  "Shopee", "Shopping Macapá", "Sicoob", "Sicredi", "Siemens", "Sky Brasil",
  "Sodexo", "Softplan", "Solana", "SOMOS Educação", "Sony", "Sorteves Rochinha",
  "Souza Cruz", "Spark", "Spring Wireless", "Stark Brand", "Stefanini", "Stone",
  "Sulamerica Seguros", "SumUp", "Suzano", "Syngenta", "Tagme", "Tata Consultancy",
  "Taurus Armas", "TecBan", "Tecnous", "Telefonica", "Tempo Assist", "Tenda",
  "Tennis", "Terra", "Terral Shopping Center", "The Nature Conservancy",
  "Thomson Reuters Brasil", "Thymus Branding", "TikTok", "TIM", "Tinder",
  "TIVIT", "Tokio Marine", "Torrent Pharma", "TOTVS", "Toyota",
  "Tozzine Freire Advogados", "Tricporp", "Tudo Farma", "TV Ceará", "TV Globo",
  "TV Metropole", "TV Record", "Uber", "UFMT", "UFRJ", "Unibanco Seguros",
  "Unico IDTech", "Unicred", "Unidas Rent a car", "Unifies", "UNIFIESP",
  "Unilever", "Unimed", "United Mills", "Universal Music", "Universidade Anhembi Morumbi",
  "Universidade Católica de Pelotas", "Universidade Católica de Santa Catarina",
  "Universidade de Brasilia", "Universidade de Vassouras (USS)",
  "Universidade do Estado do Matro Grosso", "Universidade Federal de Paraná",
  "Universidade Federal de São João Del Rei", "UOL", "Usina Aimorés", "Vale",
  "Valor Economico", "Vela", "Via Varejo", "Viação Cometa", "Viavendas",
  "Vigor Alimentos", "Virgin Media", "Vivara", "VIVO", "Volkswagen Brasil",
  "Volkswagen Argentina", "Voltz Capital", "VTEX", "Walmart", "Western Union",
  "Whirlpool", "Wiser Educaçao", "With", "Wizard Idiomas", "WMcCann",
  "World Bank", "Wunderman", "X (Twitter)", "Xerox", "XP", "Yahoo",
  "Yara International", "Yazigi", "Yellot", "Ypê", "Ypiranga", "Zendesk"
];

// Identify major brands for highlighting
export const MAJOR_BRANDS = [
  "Accenture", "Amazon", "Ambev", "American Express", "Apple", "Bank of America", 
  "Bradesco", "Burger King", "Carrefour", "Citibank", "Coca-Cola", "Dell", 
  "Disney", "Facebook", "Meta (Facebook)", "Ford", "Google", "HP", "IBM", "Intel", 
  "Itaú", "Johnson & Johnson", "McDonald’s", "Mc Donald’s", "Microsoft", "Nestlé", 
  "Nike", "Oracle", "Pepsi", "Petrobras", "Samsung", "Santander", "Shell", 
  "Uber", "Unilever", "Visa", "Volkswagen", "Volkswagen Brasil", "Volkswagen Argentina", 
  "Walmart", "X (Twitter)", "YouTube", "TikTok", "Linkedin", "Netflix", "Spotify",
  "Salesforce", "SAP", "Sony", "Toyota", "Honda", "Hyundai", "Nissan", "Mercedes Bens",
  "BMW", "Audi", "Porsche", "Porche", "Ferrari", "Lamborghini", "Tesla", "SpaceX",
  "Boeing", "Airbus", "Embraer", "General Motors", "General Motors Brasil", "FIAT",
  "Renault", "Peugeot", "Citroen", "Jeep", "Land Rover", "Jaguar", "Volvo", "Scania",
  "Heineken", "Heinkein", "Budweiser", "Corona", "Stella Artois", "Guinness",
  "Red Bull", "Monster", "Gatorade", "Powerade", "L'Oreal", "L' occitane", "Nivea", "Nívea",
  "Dove", "Pantene", "Gillette", "Colgate", "Oral-B", "Listerine", "Avon", "Natura",
  "O Boticario", "Grupo Boticário", "Sephora", "MAC", "Estee Lauder", "Clinique",
  "Lancome", "Dior", "Chanel", "Gucci", "Prada", "Louis Vuitton", "Hermes",
  "Rolex", "Omega", "Tag Heuer", "Breitling", "Patek Philippe", "Audemars Piguet",
  "Cartier", "Tiffany", "Bulgari", "Swarovski", "Pandora", "Zara", "H&M", "Uniqlo",
  "Gap", "Old Navy", "Banana Republic", "Levis", "Levi’s", "Adidas", "Puma", "Reebok",
  "Under Armour", "New Balance", "Asics", "Mizuno", "Fila", "Vans", "Converse",
  "Crocs", "Havaianas", "Melissa", "Clube Melissa", "Arezzo", "Schutz", "Anacapri",
  "Farm", "Animale", "Osklen", "Reserva", "Ellus", "Colcci", "Forum", "Triton",
  "Cavalera", "Riachuelo", "Renner", "C&A", "Marisa", "Pernambucanas", "Casas Bahia",
  "Magazine Luiza", "Ponto Frio", "Fast Shop", "Americanas", "Submarino", "Shoptime",
  "Mercado Livre", "Amazon", "Alibaba", "AliExpress", "Shopee", "Shein", "Wish",
  "Ebay", "Craigslist", "Olx", "Zap", "VivaReal", "QuintoAndar", "Loft", "Airbnb",
  "Booking", "Expedia", "TripAdvisor", "Trivago", "Kayak", "Skyscanner", "Decolar",
  "CVC", "Azul", "Gol", "GOL", "Latam", "LATAM Airlines", "Avianca", "United", "American",
  "Delta", "Lufthansa", "Air France", "KLM", "British Airways", "Emirates", "Qatar",
  "Etihad", "Turkish", "Tap", "Alitalia", "Iberia", "Aerolineas Argentinas", "Copa",
  "Aeromexico", "Air Canada", "Qantas", "Singapore", "Cathay", "Ana", "Jal",
  "Korean", "China Southern", "China Eastern", "Air China", "Hainan", "Eva",
  "Garuda", "Thai", "Malaysia", "Vietnam", "Philippine", "Cebu", "AirAsia",
  "JetBlue", "Southwest", "Spirit", "Frontier", "Alaska", "Hawaiian", "Virgin",
  "Ryanair", "EasyJet", "Wizz", "Norwegian", "Vueling", "Eurowings", "Transavia"
];
